In [13]:
from scipy.io import loadmat
import numpy as np

In [14]:
data = loadmat('salinas_pixel_remove.mat')

In [15]:
X = data['Y']

In [16]:
X.shape

(391, 224)

In [17]:
gtLabel = data['L']
gtLabel.shape

(1, 391)

In [18]:
np.where(gtLabel == 1)

(array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0], dtype=int64),
 array([ 21,  31,  50,  57,  64,  85,  96, 114, 122, 129, 149, 159, 178,
        185, 193, 213, 224, 242, 250, 259, 278, 288, 307, 314, 323, 342,
        353, 371, 379, 389], dtype=int64))

In [44]:
X = np.random.rand(2, 3, 4)

In [45]:
print(X.shape, X)

(2, 3, 4) [[[0.49236128 0.96105335 0.80476631 0.24533258]
  [0.54774286 0.32037856 0.77072862 0.87335168]
  [0.57880099 0.17231234 0.09701883 0.05212166]]

 [[0.62783016 0.32130091 0.16909731 0.12713667]
  [0.41240169 0.83047327 0.75651639 0.60399234]
  [0.71380558 0.33676879 0.62349751 0.62702005]]]


In [46]:
x = X[:, :, 0]
x

array([[0.49236128, 0.54774286, 0.57880099],
       [0.62783016, 0.41240169, 0.71380558]])

In [47]:
X = X.transpose(1, 0, 2)
print(X.shape, X)

(3, 2, 4) [[[0.49236128 0.96105335 0.80476631 0.24533258]
  [0.62783016 0.32130091 0.16909731 0.12713667]]

 [[0.54774286 0.32037856 0.77072862 0.87335168]
  [0.41240169 0.83047327 0.75651639 0.60399234]]

 [[0.57880099 0.17231234 0.09701883 0.05212166]
  [0.71380558 0.33676879 0.62349751 0.62702005]]]


In [48]:
X = X.transpose(1, 0, 2).reshape(X.shape[0]* X.shape[1], -1)
X

array([[0.49236128, 0.96105335, 0.80476631, 0.24533258],
       [0.54774286, 0.32037856, 0.77072862, 0.87335168],
       [0.57880099, 0.17231234, 0.09701883, 0.05212166],
       [0.62783016, 0.32130091, 0.16909731, 0.12713667],
       [0.41240169, 0.83047327, 0.75651639, 0.60399234],
       [0.71380558, 0.33676879, 0.62349751, 0.62702005]])

In [50]:
a = np.random.rand(2, 3)
a

array([[0.33342937, 0.19174196, 0.94709115],
       [0.50282399, 0.43574555, 0.88410926]])

In [51]:
a.reshape(a.shape[0]* a.shape[1], -1)

array([[0.33342937],
       [0.19174196],
       [0.94709115],
       [0.50282399],
       [0.43574555],
       [0.88410926]])

In [38]:
a = a.T
a.reshape(a.shape[0]* a.shape[1], -1)

array([[0.32617616],
       [0.70906978],
       [0.70189989],
       [0.84099536],
       [0.44002016],
       [0.08714317]])